version: "3.1"
services:
  db:
    ports:
      - 5433:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    volumes:
      - /custom/mount:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: app_img
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prod
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    restart: always
